[build]
# https://docs.netlify.com/build/configure-builds/manage-dependencies/#node-js-and-javascript
# Node version set in .nvmrc
# JS dependencies must be listed in package.json
command = "npm run build"
publish = "dist/"

# Redirect rules
# Splat redirect from /docs/<lang>/ to /en
# For example /docs/es/overview to /docs/en/overview
# As en is currently the only locale
[[redirects]]
  from = "/docs/:lang/:slug"
  to = "/docs/en/:slug"
  status = 302
# Splat redirect from /docs/ to /
# Previously the site was severed at allcontributors.org/docs/
[[redirects]]
  from = "/docs/*"
  to = "/:splat"
  status = 302
